### ISSUE TITLE
Docs: เรียกใช้ Vue.component

### ISSUE THREAD

**Issue by runyasak** [biigpongsatorn/vue-thailand-address-autocomplete#1]
จาก [Docs](https://biigpongsatorn.github.io/#/vue-thailand-address-autocompleter) อะครับ
เวลาเรียกใช้ Vue.component ต้องใส่ชื่อ tag เจาะจงที่จะใช้เลยครับ
ถ้าอยากให้สามารถใช้ tag `<ThailandAutoComplete />` ได้ต้องประกาศว่า

`Vue.component('ThailandAutoComplete', ThailandAutoComplete)`

ครับผม

ที่มา: https://vuejs.org/v2/guide/components-registration.html#Component-Names

**Comment by biigpongsatorn** [comment]
@runyasak 
Done thank you kub
